all: 
	$(MAKE) -C scalar
	$(MAKE) -C vector
	$(MAKE) -C vector_blas
	$(MAKE) -C matrix

clean:
	- $(MAKE) -C scalar clean
	- $(MAKE) -C vector clean
	- $(MAKE) -C vector_blas clean
	- $(MAKE) -C matrix clean
